### ISSUE TITLE
Cannot compile on GCC 10.1.0

### ISSUE THREAD

**Issue by RockfordRoe** [mupen64plus/mupen64plus-rsp-cxd4#49]
Project version: Git 
OS: Gentoo GNU/Linux
Compiler: gcc (Gentoo 10.1.0 p1) 10.1.0

Without modifying the Makefile in projects/unix, gcc returns:
```    CC  _obj-sse2/su.o
    CC  _obj-sse2/vu/divide.o
    CC  _obj-sse2/vu/logical.o
    CC  _obj-sse2/vu/add.o
    CC  _obj-sse2/vu/multiply.o
../..//vu/add.c: In function ‘do_abs’:
../..//vu/add.c:165:2: warning: implicit declaration of function ‘memset’ [-Wimplicit-function-declaration]
  165 |  memset(&nez, 0, sizeof(nez));
      |  ^~~~~~
../..//vu/add.c:165:2: warning: incompatible implicit declaration of built-in function ‘memset’
../..//vu/add.c:17:1: note: include ‘<string.h>’ or provide a declaration of ‘memset’
   16 | #include "add.h"
  +++ |+#include <string.h>
   17 | 
    CC  _obj-sse2/vu/select.o
    CC  _obj-sse2/vu/vu.o
    CC  _obj-sse2/module.o
    CC  _obj-sse2/osal_dynamiclib_unix.o
    LD  mupen64plus-rsp-cxd4-sse2.so
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: _obj-sse2/module.o (symbol from plugin): in function `RSP_info':
(.text+0x0): multiple definition of `CPR_specifier'; _obj-sse2/su.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:330: mupen64plus-rsp-cxd4-sse2.so] Error 1
```

But setting CC to clang seems to make it compile correctly.

```
    CC  _obj/vu/add.o
    CC  _obj/vu/divide.o
    CC  _obj/su.o
    CC  _obj/vu/logical.o
    CC  _obj/vu/multiply.o
../..//vu/add.c:165:2: warning: misleading indentation; statement is not part of the previous 'for' [-Wmisleading-indentation]
        memset(&nez, 0, sizeof(nez));
        ^
../..//vu/add.c:162:5: note: previous statement is here
    for (i = 0; i < N; i++)
    ^
../..//vu/add.c:165:2: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
        memset(&nez, 0, sizeof(nez));
        ^
../..//vu/add.c:165:2: note: include the header <string.h> or explicitly provide a declaration for 'memset'
    CC  _obj/vu/select.o
    CC  _obj/vu/vu.o
    CC  _obj/module.o
2 warnings generated.
    CC  _obj/osal_dynamiclib_unix.o
    LD  mupen64plus-rsp-cxd4.so
```

**Comment by richard42** [comment]
thanks for the report. this error should be fixed now.

**Comment by RockfordRoe** [comment]
Even after the commit, it still doesn't seem to compile correctly. 

```/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: _obj-sse2/module.o (symbol from plugin): in function `RSP_info':
(.text+0x0): multiple definition of `CPR_specifier'; _obj-sse2/su.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:330: mupen64plus-rsp-cxd4-sse2.so] Error 1```

**Comment by richard42** [comment]
Unfortunately I don't have GCC 10 to test with, but I did fix this and a couple of other potential issues.  Can you please try again?
